spring.application.name=transactionService
server.port=8085
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://ep-weathered-silence-a1kiwre1-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&currentSchema=public
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KFWCLdq0Qj2D
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
