package com.payPanda.entity;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Table(name = "merchant")
@Data
public class MerchantEntity {

    @Id
    @Column(name = "merchant_id", length = 7)
    private String merchantId;           // Unique 7-digit code — generated by service

    @Column(name = "merchant_name", length = 100, nullable = false)
    private String merchantName;

    @Column(name = "email", length = 100, nullable = false)
    private String email;                // Mandatory

    @Column(name = "mobile_number", length = 15, nullable = false)
    private String mobileNumber;         // Mandatory

    @Column(name = "bank_name", length = 100)
    private String bankName;             // Optional

    @Column(name = "account_number", length = 20)
    private String accountNumber;        // Optional

    @Column(name = "ifsc_code", length = 11)
    private String ifscCode;             // Optional

    @Column(name = "status", length = 20, nullable = false)
    private String status; 
    
    // "Active" or "Closed"
    
}